<template>
  <div id="regionBox">
    <div id="regionSelect">
      <span>REGION SELECT</span><br>
      <button
        id="kantoButton"
        onclick="userInteractions.goToKanto()"
        class="button"
        value="Kanto"
      >
        Kanto
      </button>
      <button
        id="johtoButton"
        onclick="userInteractions.goToJohto()"
        class="button"
        value="Johto"
      >
        Johto
      </button>
      <button
        id="hoennButton"
        onclick="userInteractions.goToHoenn()"
        class="button"
        value="Hoenn"
      >
        Hoenn
      </button><br>
      <button
        id="sinnohButton"
        onclick="userInteractions.goToSinnoh()"
        class="button"
        value="Sinnoh"
      >
        Sinnoh
      </button>
      <button
        id="fioreButton"
        onclick="userInteractions.goToFiore()"
        class="button"
        value="Fiore"
      >
        Fiore
      </button>
      <button
        id="unovaButton"
        onclick="userInteractions.goToUnova()"
        class="button"
        value="Unova"
      >
        Unova
      </button><br>
      <button
        id="kalosButton"
        onclick="userInteractions.goToKalos()"
        class="button"
        value="Kalos"
      >
        Kalos
      </button>
      <button
        id="alolaButton"
        onclick="userInteractions.goToAlola()"
        class="button"
        value="Alola"
      >
        Alola
      </button>
      <button
        id="galarButton"
        onclick="userInteractions.goToNone()"
        class="button"
        value="Galar"
      >
        Galar
      </button><br>
    </div>
  </div>
</template>
